language: python
python:
  - "3.6"
  - "3.7-dev"
matrix:
  fast_finish: true
before_install:
  - pip install pytest-cov
install:
  - pip install -e ".[cloudflare]"
script:
  - python -m pytest tests --cov=.
after_success:
  - pip install codecov
  - codecov
