pip-run: &pip-install
  name: Install Python dependencies
  command: |
    python3 -m venv venv
    . venv/bin/activate
    pip install pytest
    pip install -e .


version: 2
jobs:
  nineanime:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: *pip-install
      - run: venv/bin/python -m pytest tests/test_anime.py --anime-url https://www4.9anime.is/watch/kochinpa.p6l6/j6ooy2

workflows:
  version: 2
  nightly:
    jobs:
      - nineanime

    # triggers:
    #   - schedule:
    #       cron: "0 0 * * *"
          # filters:
          #   branches:
          #     only:
          #       - master
